@startuml
left to right direction
actor 学生 #DDDDDD;line:black;line.bold;
actor 教員 #DDDDDD;line:black;line.bold;
actor 管理者 #DDDDDD;line:black;line.bold;
rectangle 就職活動報告書管理システム {
    usecase ログアウト
    usecase メニュー
    usecase 報告書を作成
    usecase 報告書を教員に提出
    usecase 報告書の検索
    usecase 報告書の閲覧
    usecase 報告書の編集
    usecase 学生が提出した報告書の確認
    usecase 学生が提出した報告書を提出
    usecase 報告書を学生に返却
    usecase メールを送信
    usecase 教員が提出した報告書の確認
    usecase 報告書を教員に返却
    usecase 報告書を承認
    usecase アカウントの作成
    usecase アカウントの編集
    usecase アカウントの削除
    usecase (<u>ログイン</u>\n拡張点\nアカウント未登録) as input_login
    }
学生 --> アカウントの作成
学生 --> input_login
学生 --> 報告書の検索
学生 --> 報告書の閲覧
教員 --> input_login
教員 --> 報告書の検索
教員 --> 報告書の閲覧
教員 --> 報告書を教員に提出
教員 --> 学生が提出した報告書を提出
教員 --> 報告書を学生に返却
教員 --> メールを送信
管理者 --> input_login
管理者 --> 報告書の検索
管理者 --> 報告書の閲覧
管理者 --> 教員が提出した報告書の確認
管理者 --> 報告書を教員に返却
管理者 --> 報告書を承認
管理者 --> メールを送信
管理者 --> アカウントの作成
管理者 --> アカウントの編集
管理者 --> アカウントの削除
管理者 --> アカウントの作成
管理者 --> アカウントの編集
管理者 --> アカウントの削除
管理者 --> アカウントの作成
管理者 --> アカウントの編集
管理者 --> アカウントの削除
アカウントの作成 .> input_login
報告書を作成 --> 報告書を教員に提出
input_login --> メニュー
メニュー --> ログアウト
メニュー --> 報告書の検索
メニュー --> 報告書の閲覧
メニュー --> 報告書を作成
メニュー --> 報告書の編集
報告書を教員に提出 --> 報告書を学生に返却
報告書を学生に返却 --> メールを送信
学生が提出した報告書を提出 --> 管理者

@enduml