@startuml 就職活動報告書管理システムB
left to right direction
actor 学生 #DDDDDD;line:black;line.bold;
actor 教員 #DDDDDD;line:black;line.bold;
actor 管理者 #DDDDDD;line:black;line.bold;
rectangle 就職活動報告書管理システムB {
    usecase アカウント作成
    usecase アカウント編集
    usecase アカウント削除
    usecase ログイン
    usecase ログアウト
    usecase 報告書作成
    usecase 報告書提出
    usecase 報告書検索
    usecase 報告書閲覧
    usecase 報告書編集
    usecase 報告書確認
    usecase 報告書返却
    usecase 報告書承認
    usecase メール送信
}
学生 --> アカウント作成
学生 --> ログイン
学生 --> ログアウト
学生 --> 報告書作成
学生 --> 報告書提出
学生 --> 報告書検索
学生 --> 報告書閲覧
教員 ---> ログイン
教員 ---> ログアウト
教員 ---> 報告書提出
教員 ---> 報告書検索
教員 ---> 報告書閲覧
教員 ---> 報告書確認
教員 ---> 報告書返却
教員 ---> メール送信
アカウント作成 <---- 管理者
アカウント編集 <--- 管理者
アカウント削除 <--- 管理者
ログイン <-- 管理者
ログアウト <-- 管理者
報告書検索 <-- 管理者
報告書閲覧 <-- 管理者
報告書編集 <-- 管理者
報告書確認 <-- 管理者
報告書返却 <-- 管理者
報告書承認 <-- 管理者
メール送信 <-- 管理者
@enduml