@startuml データ更新コントローラとホテルと予約
hide footbox
 'メッセージに自動で番号を降る
 autonumber
 ' 厳密なUMLに準拠する
skinparam style strictuml

participant "<u>:controller" as ct
participant "<u>:hotel" as ht

activate ct
    ct -> ht:予約操作()
activate ht

    create "<u>:予約" as yo
    ht -->> yo :<<create>>
    ht -> ht:予約登録()

    activate ht
deactivate ct

deactivate ht
@enduml