@startuml 演習6-3-2

[*] -right->メニュー
メニュー-right->[*]
メニュー--> 予約と確認 :予約ボタン
予約と確認--> メニュー :取り消しボタン
あなたの順番 -up-> メニュー :メニューボタン
メニュー-down-> 今の順番 :今の順番ボタン
今の順番-up-> メニュー :メニューボタン
予約と確認-right-> あなたの順番 :名前と電話番号
予約と確認-right-> あなたの順番 :現在の登録者番号

@enduml
