@startuml ユースケース図
rectangle ホテルの宿泊予約システム{
usecase ログインをする
usecase キャンペーン内容
usecase (<u>予約をする</u>\n拡張点\nキャンペーン期間) as input
}
input .> ログインをする: <<include>>
利用者 --> input
(キャンペーン内容) .> input: <<extend>>
@enduml