@startuml 演習4-6

hide footbox

skinparam style strictuml /' 厳密なUMLに準拠する'/
Actor ":顧客" as user
participant ":ブラウザ" as browser
participant ":Webサーバ" as webserver
participant ":画像サーバ" as server

activate user
user -> browser : リンクボタンを押す
activate browser
browser -> webserver : ファイル名を伝える
activate webserver
webserver -> server : 該当するファイル名を渡す
activate server
server -> server : ファイルを探す
webserver <<-- server : 画像ファイル
browser <<-- webserver : 画像ファイルを再生
user <<-- browser : 画像閲覧

@enduml