@startuml 演習3-4-2
skinparam classAttributeIconSize 0
left to right direction
class 車 {
- 車種:String
- メーカー:String
}
class タイヤ {
- タイヤ種類:String
- 大きさ:int
- 料金:int
---
+ 取り付ける():void
}
hide 車 circle
hide タイヤ circle
車--"4"タイヤ
hide circle
@enduml
